In [ ]:
# Task 1.1 

In [7]:
import numpy as np
import numpy.linalg as la

In [11]:
# Create a  matrix with sample values
T = np.array([
    [0.8, 0, 0.2, 0],
    [0.05, 0.93, 0.02, 0],
    [0.8, 0.1, 0, 0.1],
    [0.0, 0.5, 0, 0.5]
])


In [39]:
# Method 1
n=3
la.matrix_power(T, n)

array([[0.769   , 0.0446  , 0.1604  , 0.026   ],
       [0.148225, 0.810077, 0.037838, 0.00386 ],
       [0.65275 , 0.17419 , 0.13186 , 0.0412  ],
       [0.06375 , 0.79095 , 0.0193  , 0.126   ]])

In [17]:
n=1000
la.matrix_power(T, n)

array([[0.53745928, 0.3257329 , 0.11400651, 0.0228013 ],
       [0.53745928, 0.3257329 , 0.11400651, 0.0228013 ],
       [0.53745928, 0.3257329 , 0.11400651, 0.0228013 ],
       [0.53745928, 0.3257329 , 0.11400651, 0.0228013 ]])

In [41]:
# Method 2: using eigenvector & eigenvalue 

In [19]:
eigenvalues, eigenvectors = np.linalg.eig(T)

In [25]:
#Raise the diagonal matrix of eigenvalues to the desired power:
n = 3
power_n = np.diag(eigenvalues ** n)

In [27]:
#Compute the inverse of the eigenvector matrix:
Q_inv = np.linalg.inv(eigenvectors)

In [33]:
T2 = eigenvectors @ power_n @ Q_inv

In [35]:
T2

array([[0.769   , 0.0446  , 0.1604  , 0.026   ],
       [0.148225, 0.810077, 0.037838, 0.00386 ],
       [0.65275 , 0.17419 , 0.13186 , 0.0412  ],
       [0.06375 , 0.79095 , 0.0193  , 0.126   ]])